export const RECEIVED_CHART_METRICS = 'RECEIVED_CHART_METRICS';
export const RECEIVED_METRICS_TAGS = 'RECEIVED_METRICS_TAGS';
export const TOGGLE_SELECTED_METRIC = 'TOGGLE_SELECTED_METRIC';
export const RECEIVED_METRICS_LAST_MEASUREMENTS = 'RECEIVED_METRICS_LAST_MEASUREMENTS';
export const UPDATED_METRIC_VALUE = 'UPDATED_METRIC_VALUE';
export const REPLACE_LAST_CHART_VALUE = 'REPLACE_LAST_CHART_VALUE';
